"""
ELARA - AI Action Generator
This module generates structured actions from natural language using LLM.
"""

from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass
import json

from app.ai.intent_parser import Intent, IntentCategory, IntentAction
from app.ai.llm_provider import LLMProviderManager
from app.actions.registry import ActionRegistry
from app.utils.logger import get_logger


@dataclass
class GeneratedAction:
    """Represents an action generated by AI."""
    action_id: str
    action_name: str
    parameters: Dict[str, Any]
    confidence: float
    reasoning: str
    is_valid: bool
    validation_errors: List[str]


class ActionGenerator:
    """Generates structured actions from natural language using AI."""
    
    def __init__(self, llm_manager: Optional[LLMProviderManager] = None):
        self.logger = get_logger("elara.action_generator")
        
        self.llm_manager = llm_manager or LLMProviderManager()
        self.action_registry = ActionRegistry()
        
        # System prompt for action generation
        self.system_prompt = """You are ELARA, a Windows AI assistant. Your task is to understand user requests and convert them into structured actions.

Available action categories:
- application: open_application, close_application
- window: minimize_window, maximize_window, restore_window
- volume: volume_up, volume_down, set_volume, mute, unmute
- screenshot: take_screenshot
- system: lock_computer, restart_computer, shutdown_computer, sleep_computer, log_off
- file: open_folder, create_folder
- browser: open_url, browser_search
- information: get_system_info, get_time

You must respond with valid JSON in this format:
{
    "action_id": "action_name",
    "parameters": {"key": "value"},
    "confidence": 0.95,
    "reasoning": "Explanation of why this action was chosen"
}

Be conservative - if you're not confident, set confidence low. If the request is unclear or dangerous, indicate it in reasoning."""
    
    def generate_action_from_text(self, text: str) -> GeneratedAction:
        """
        Generate a structured action from natural language text.
        
        Args:
            text: User input text
            
        Returns:
            Generated action object
        """
        self.logger.info(f"Generating action from text: '{text}'")
        
        # First, try rule-based intent parsing for faster, more predictable results
        from app.ai.intent_parser import IntentParser
        intent_parser = IntentParser()
        intent = intent_parser.parse(text)
        
        # If we have high confidence from rule-based parsing, use that
        if intent.confidence >= 0.8 and intent.action != IntentAction.UNKNOWN_ACTION:
            return self._convert_intent_to_action(intent)
        
        # Otherwise, use LLM for more complex understanding
        return self._generate_action_with_llm(text)
    
    def _convert_intent_to_action(self, intent: Intent) -> GeneratedAction:
        """
        Convert a parsed intent to a generated action.
        
        Args:
            intent: Parsed intent object
            
        Returns:
            Generated action object
        """
        action_id = intent.action.value
        action_name = intent.action.value.replace("_", " ").title()
        
        # Validate action exists in registry
        action_exists = self.action_registry.action_exists(action_id)
        
        # Build reasoning
        reasoning = f"Detected {intent.category.value} intent with action {action_id}"
        if intent.parameters:
            reasoning += f" with parameters: {intent.parameters}"
        
        return GeneratedAction(
            action_id=action_id,
            action_name=action_name,
            parameters=intent.parameters,
            confidence=intent.confidence,
            reasoning=reasoning,
            is_valid=action_exists,
            validation_errors=[] if action_exists else [f"Action {action_id} not registered"]
        )
    
    def _generate_action_with_llm(self, text: str) -> GeneratedAction:
        """
        Generate action using LLM for complex understanding.
        
        Args:
            text: User input text
            
        Returns:
            Generated action object
        """
        try:
            # Generate structured response from LLM
            response = self.llm_manager.generate_structured_response(
                prompt=text,
                system_prompt=self.system_prompt,
                schema={
                    "type": "object",
                    "properties": {
                        "action_id": {"type": "string"},
                        "parameters": {"type": "object"},
                        "confidence": {"type": "number"},
                        "reasoning": {"type": "string"}
                    },
                    "required": ["action_id", "parameters", "confidence", "reasoning"]
                }
            )
            
            # Validate the generated action
            is_valid, validation_errors = self._validate_generated_action(response)
            
            return GeneratedAction(
                action_id=response.get("action_id", "unknown"),
                action_name=response.get("action_id", "unknown").replace("_", " ").title(),
                parameters=response.get("parameters", {}),
                confidence=response.get("confidence", 0.5),
                reasoning=response.get("reasoning", "No reasoning provided"),
                is_valid=is_valid,
                validation_errors=validation_errors
            )
            
        except Exception as e:
            self.logger.error(f"LLM action generation failed: {e}")
            
            # Fallback to unknown action
            return GeneratedAction(
                action_id="unknown",
                action_name="Unknown Action",
                parameters={},
                confidence=0.0,
                reasoning=f"LLM generation failed: {str(e)}",
                is_valid=False,
                validation_errors=["LLM generation failed"]
            )
    
    def _validate_generated_action(self, response: Dict[str, Any]) -> Tuple[bool, List[str]]:
        """
        Validate a generated action against the action registry.
        
        Args:
            response: LLM response dictionary
            
        Returns:
            Tuple of (is_valid, validation_errors)
        """
        validation_errors = []
        
        action_id = response.get("action_id")
        if not action_id:
            validation_errors.append("Missing action_id")
            return False, validation_errors
        
        # Check if action exists in registry
        if not self.action_registry.action_exists(action_id):
            validation_errors.append(f"Action '{action_id}' not registered in action registry")
        
        # Validate parameters against action schema
        action = self.action_registry.get_action(action_id)
        if action:
            is_valid_params, param_errors = self.action_registry.validate_parameters(
                action_id, 
                response.get("parameters", {})
            )
            if not is_valid_params:
                validation_errors.extend(param_errors)
        
        # Check confidence
        confidence = response.get("confidence", 0.0)
        if confidence < 0.5:
            validation_errors.append(f"Low confidence: {confidence}")
        
        return len(validation_errors) == 0, validation_errors
    
    def generate_action_sequence(self, text: str) -> List[GeneratedAction]:
        """
        Generate a sequence of actions for complex requests.
        
        Args:
            text: User input text that may require multiple actions
            
        Returns:
            List of generated actions
        """
        self.logger.info(f"Generating action sequence from text: '{text}'")
        
        # For now, just return single action
        # In the future, this could use LLM to detect multi-step requests
        action = self.generate_action_from_text(text)
        return [action]
    
    def clarify_ambiguous_request(self, text: str) -> str:
        """
        Generate a clarification question for ambiguous requests.
        
        Args:
            text: Ambiguous user input text
            
        Returns:
            Clarification question
        """
        clarification_prompt = f"""The user said: "{text}"

This request is ambiguous. Generate a brief, natural clarification question to help understand what they want.
Keep it concise and conversational. Start directly with the question."""

        try:
            response = self.llm_manager.generate_response(
                prompt=clarification_prompt,
                system_prompt="You are ELARA, a helpful AI assistant. Ask brief clarification questions."
            )
            return response.strip()
        except Exception as e:
            self.logger.error(f"Clarification generation failed: {e}")
            return "Could you please clarify what you'd like me to do?"
    
    def suggest_related_actions(self, text: str) -> List[str]:
        """
        Suggest related actions based on user input.
        
        Args:
            text: User input text
            
        Returns:
            List of suggested action descriptions
        """
        suggestions_prompt = f"""Based on the user request: "{text}"

Suggest 3-5 related actions they might want to perform next.
Return as a JSON array of action descriptions (e.g., ["Open Chrome", "Take a screenshot", "Check system info"])."""

        try:
            response = self.llm_manager.generate_structured_response(
                prompt=suggestions_prompt,
                system_prompt="You are ELARA, a helpful AI assistant. Suggest related actions.",
                schema={
                    "type": "array",
                    "items": {"type": "string"}
                }
            )
            return response if isinstance(response, list) else []
        except Exception as e:
            self.logger.error(f"Suggestion generation failed: {e}")
            return []
    
    def get_action_help(self, action_id: str) -> str:
        """
        Get help text for a specific action.
        
        Args:
            action_id: Action identifier
            
        Returns:
            Help text description
        """
        action = self.action_registry.get_action(action_id)
        if action:
            help_text = f"**{action.name}**\n\n{action.description}\n\n"
            
            if action.parameters:
                help_text += "**Parameters:**\n"
                for param_name, param_info in action.parameters.items():
                    required = param_info.get("required", False)
                    param_type = param_info.get("type", "unknown")
                    description = param_info.get("description", "")
                    help_text += f"- {param_name} ({param_type}){' [required]' if required else ''}: {description}\n"
            
            return help_text
        else:
            return f"Action '{action_id}' not found. Available actions: {', '.join(self.action_registry.get_all_actions().keys())}"
    
    def explain_action(self, action_id: str, parameters: Dict[str, Any]) -> str:
        """
        Generate a natural language explanation of what an action will do.
        
        Args:
            action_id: Action identifier
            parameters: Action parameters
            
        Returns:
            Natural language explanation
        """
        action = self.action_registry.get_action(action_id)
        if not action:
            return f"Unknown action: {action_id}"
        
        explanation_prompt = f"""Explain what this action will do in simple terms:
Action: {action.name}
Description: {action.description}
Parameters: {json.dumps(parameters, indent=2)}

Provide a clear, concise explanation for the user."""

        try:
            response = self.llm_manager.generate_response(
                prompt=explanation_prompt,
                system_prompt="You are ELARA, a helpful AI assistant. Explain actions clearly and concisely."
            )
            return response.strip()
        except Exception as e:
            self.logger.error(f"Explanation generation failed: {e}")
            return f"This will {action.description.lower()} with the provided parameters."
